server:
  port: 8093

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/smu_poodle?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create

    open-in-view: false
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

