server:
    port: 8081

spring:
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/voca_team2?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: root
        hikari:
            driver-class-name: com.mysql.cj.jdbc.Driver
    thymeleaf:
        cache: false

    jpa:
        hibernate:
            ddl-auto: update

        open-in-view: false
        show-sql: true

    main:
        allow-bean-definition-overriding=true:

logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.type: trace
